[package]
name = "whispr-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
cpal = "0.15"
tokio-tungstenite = "0.24"
futures-util = "0.3"
dirs = "5"

[dev-dependencies]
hound = "3"
tracing-subscriber.workspace = true
clap = { version = "4", features = ["derive"] }

[[example]]
name = "whispr-cli"
path = "examples/whispr_cli.rs"
